### PR TITLE
Add hidden props

### PR DESCRIPTION
**Pull request by ajaxangular**
Set hidden props true on any item to hide this item from drawer section

### CODE REVIEW

**Comment by xotahal** [comment]
Why do you need that?

**Comment by ajaxangular** [comment]
I think it maybe useful in login/logout menu. When user successfully login then login menu will be hidden and logout menu will be shown, vice versa. I know there are so many ways to implementing this hidden login/logout menu, but since you have the disabled props why not have the hidden props too? :)

**Comment by xotahal** [comment]
I see. But it's enought to set `items` prop, isn't?

**Comment by ajaxangular** [comment]
yeah you right, as I said that there were other ways to achieve it. Below is my code implementing hidden props to item prop

}, {

    icon: 'verified-user',
    value: 'Add Sub Account',
    active: routeName === 'RegisterSubAccountScreen',
    onPress: () => this.props.navigateTo('RegisterSubAccountScreen'),
    onLongPress: () => this.props.navigateTo('RegisterSubAccountScreen'),
    hidden: this.props.isLogged ? false : true
}, {

    icon: 'face',
    value: 'Login',
    active: !routeName || routeName === 'LoginScreen',
    onPress: () => this.props.navigateTo('LoginScreen'),
    onLongPress: () => this.props.navigateTo('LoginScreen'),
    hidden: !this.props.isLogged ? false : true
}, {

    icon: 'exit-to-app',
    value: 'Logout',
    active: !routeName || routeName === 'LogoutScreen',
    onPress: () => this.props.navigateTo('LogoutScreen'),
    onLongPress: () => this.props.navigateTo('LogoutScreen'),
    hidden: this.props.isLogged ? false : true
}

**Comment by xotahal** [comment]
Actually I would like to make it simpler. It should be just about style. Hidden property is more about what is rendered and what is not. Try this solution please:

```js
const items = []

if (this.props.isLogged) {
   items.push({ .... })
}
```
It produces same result and we don't have to do any changes in library.

**Comment by ajaxangular** [comment]
With hidden props it may have advantages to sort the item as we like and it's more flexible and natural to use. With push we can only put the item below other item.

**Pull request closed without merging**
