### PR TITLE
[BottomNavigation] Added component

### PR DESCRIPTION
**Pull request by HofmannZ**
Hey,

I found some time to do a quick pull request, I created a Bottom Navigation component as described in the Material Design Guidelines [here](https://material.google.com/components/bottom-navigation.html). I could not really figure out how your Ripple Feedback component worked so feel free to tinker with that. 

I also added some docs, because that is important stuff 🤓.

Besides that, I did some minor bug fixed to the [ListItem](https://github.com/xotahal/react-native-material-ui/tree/master/src/ListItem) component. The colors were not correctly referenced from the uiTheme.palette in [getTheme.js](https://github.com/xotahal/react-native-material-ui/blob/master/src/styles/getTheme.js). 

Feel free to leave some feedback.

Ciao ✌🏼

### CODE REVIEW

**Comment by xotahal** [comment]
Thank you @HofmannZ 

Meanwhile I did it the same :D https://github.com/xotahal/react-native-material-ui/issues/32#issuecomment-264409870

I'll try to merge it together ;)

**Comment by xotahal** [comment]
Almost done guys :) Waiting for @HofmannZ to check the changes ..

untitled

**Comment by HofmannZ** [comment]
Haha, that's slightly inconvenient, but let's merge them.  I do have some show and hide animations working that I'm still tweaking but I'll adapt them to the merged version and create a new pull request for it. 

ps. Do you have some kind of project board somewhere, so we can avoid double work? The next 3 months my team and I are going to contribute to this project, would be nice to not spend time double 😅.

Ciao ✌🏼

**Comment by xotahal** [comment]
Don't have product board, but we could make some. Trello for example?

**Comment by HofmannZ** [comment]
Yeah, I think it will be a good addition. What's your Trello username, then a can create one and add you as an owner.

**Comment by mrcasals** [comment]
@xotahal @HofmannZ maybe you can try to use the Projects tab here in GitHub, so you don't need to create a separate Trello :)

**Comment by xotahal** [comment]
@mrcasals exactly, I already forget to this new feature :)

**Pull request merged**
