### PR TITLE
Fixes lint errors on Circle Ci

### PR DESCRIPTION
**Pull request by iRoachie**
Fixes lint errors on ci that make every PR fail.

### CODE REVIEW

**Comment by iRoachie** [comment]
Will make another PR for `yarn test` issues

**Comment by iRoachie** [comment]
Welcome back! @xotahal

**Comment by xotahal** [comment]
Sorry guys ... It was quite busy part of my live :)

**Comment by iRoachie** [comment]
Did you get married? 😅  Sure no problem. If you need any help I don't mind helping out with issues and PRs

**Pull request merged**
