### PR TITLE
Create getPlatformElevation.windows.js

### PR DESCRIPTION
**Pull request by sm2017**
Fix "error: bundling failed: UnableToResolveError: Unable to resolve module `./getPlatformElevation` " to be compatible with react-native-windows

### CODE REVIEW

**Comment by sm2017** [comment]
@xotahal Please reply

**Comment by sm2017** [comment]
@xotahal Can you please accept this PR??

**Comment by xotahal** [comment]
@sm2017 Hey, will do .. sorry, just saw everywhere tests are failing and don't have a lot of time to solve that right now

**Comment by sm2017** [comment]
@xotahal thanks  , but test fails are not related to my changes

**Comment by xotahal** [comment]
@sm2017 I know, I see .. have to fix that

**Pull request merged**
