### PR TITLE
ListItem: allow `numberOfLines` prop to primary text

### PR DESCRIPTION
**Pull request by kenma9123**
Please see issue #43

### CODE REVIEW

**Comment by xotahal** [comment]
Hey @kenma9123, thank you for the pull request. I'm not sure if we should change number of first line. Could you give me an example where you need it? And if we need it, we should do it separately. I mean `primaryTextLines` and `seconndaryTextLines` ([material-ui provides something similar](http://www.material-ui.com/#/components/list), but without ability to change number of first line). What do you mean?

**Comment by kenma9123** [comment]
I'm on mobile atm. 

Here's the difference.

by default - its being truncated

```
I'm a very long text inside a Lis...
```

with this PR {numberOfLines} - and we can pass like `dynamic`

```
I'm a very long text inside a
List, wrapped inside this box
```

probably another option would be good. Tho this PR can still make one liner text as long as it's not that too long or greater than the `centerElement` width.

**Comment by xotahal** [comment]
Well, I understand what does it do, and how does it do, but don't understand why does it do :) Because I think this two and more lines title makes the list item confused. I think that better way is make the title shorter :) If you understand.

But ok, I'm not against ;) Anyway, we definitely need `primaryTextLines` and `secondaryTextLines`. Because sometimes you want title to have only one line and secondary text dynamic, for example.

And we should do it back compatible. So we need all three options. `primaryTextLines`, `secondaryTextLines` and `numberOfLines` (which should be obsolete).

**Comment by kenma9123** [comment]
`numberOfLines` default value is `1` anyway, it doesn't hurt if they use it or not. If they don't set the property it will remain as `1` so it's still a backward compatible. The bad thing is that is also affects the `secondaryText`.

`numberOfLines` sometimes confusing, you don't know if it's for the `primaryText` or just for the `secondaryText` until you start using it. Maybe yes, a new property for the `primaryText` would suffice.

**Comment by xotahal** [comment]
Exactly what we should do ;) 👍 

> deprecate the numberOfLines and introduce separate options for the two text

**Comment by kenma9123** [comment]
but honestly speaking `numberOfLines` is a property of `Text` so we can't really deprecated that literally. Anyway when this going to be implemented, I have to retain this code on my copy of material ui cause I need that layout so bad.

**Pull request closed without merging**
