### PR TITLE
Fix list item subview clicks

### PR DESCRIPTION
**Pull request by xvonabur**
This PR fixes right element click, which I previously ruined with #195 (sorry for the regression!)
Basically, it returns default `pointerEvents` prop value to the `ListItem` view when the right element is present. Otherwise, it will be `box-only`.

Unfortunately, I cannot find more elegant solution right now.

### CODE REVIEW

**Comment by janziemba** [comment]
@xvonabur Thank you for this PR. I recently faced the same problem and I have removed ListItem's _pointerEvents_ in my forked repository.
In our project, we also use ListItems with TextInputs inside _centerElement_ and touchable avatars inside _leftElement_. We should support it too because sometimes you just need a list with buttons and other touchable elements, right?
Would you mind updating this PR please?

**Comment by xvonabur** [comment]
@janziemba , so basically you use custom components inside your leftElement and centerElement, right? I can try to remove pointerEvents for this case.

Would you mind to share some code snippets for your case?

**Comment by xvonabur** [comment]
@janziemba Please try the latest commit. Does it fix your case?

**Comment by janziemba** [comment]
Sorry for the late reply. Yes, that fixed my case.
What I meant was something like this:

`<ListItem leftElement="person" centerElement={<TextInput ... />}>`
screen shot 2017-10-28 at 4 58 55 pm

`<ListItem leftElement={<Avatar onPress={ ... } ... />} centerElement="Jan Ziemba">`
screen shot 2017-10-28 at 4 58 22 pm

Now everything works. Thank you.

**Comment by xvonabur** [comment]
@janziemba  👍 
@xotahal you are free to merge this

**Comment by adrianicv** [comment]
Please @xotahal if everything is ok with this PR, merge it. It would be awesome to have the rigthElements back in listItems :slightly_smiling_face: 

Thanks in advance.

**Pull request merged**
