### PR TITLE
use react-native-vector-icons 4.0 version

### PR DESCRIPTION
**Pull request by jacklam718**

### CODE REVIEW

**Comment by NewOldMax** [comment]
Does it necessary? As I see change logs of react-native-vector-icons, MateriaIcons icons isn't updated, so maybe we don't have sense to update this package...

**Comment by andrewda** [comment]
Why wouldn't we? There's no reason *not* to update the dependency as far as I can see.

**Comment by jacklam718** [comment]
@NewOldMax  I used react-naitve 0.4.2 with `react-native-material-ui` when I build I got `RCTLogLevel` error from `react-native-vector-icons` and I found other people have the same issue from react-native-vector-icons'issues. And the solution seems just upgrade vector-icons to 4.0 and it works. 

FYI: https://github.com/oblador/react-native-vector-icons/issues/375

**Comment by NewOldMax** [comment]
For me RN 0.42 and react-native-vector-icons works without errors. Weird...

**Comment by chirag04** [comment]
our app is having react-native-vector-icons v4.0. Since this lib pins to the exact version "3.0", react-native-vector-icons is included twice for us!

Ideally react-native-vector-icons should just be a peerDependency of this project.

**Comment by chirag04** [comment]
related: https://github.com/xotahal/react-native-material-ui/pull/90

**Comment by xotahal** [comment]
I approved #90. I'll close this one since is not actually ...

**Pull request closed without merging**
