### PR TITLE
Replaced View.propTypes with ViewPropTypes

### PR DESCRIPTION
**Pull request by iRoachie**
React native moved View.propTypes to ViewPropTypes. This pr makes that change, solving the warnings in console. 

See commit here https://github.com/facebook/react-native/commit/53905a537a58d028fc5eb1c4e9a8ec967d8cd396

### CODE REVIEW

**Comment by chitezh** [comment]
Yeah. eg. https://github.com/xotahal/react-native-material-ui/pull/148

**Comment by iRoachie** [comment]
@xotahal Any issues with merge?

**Comment by iRoachie** [comment]
Fixes #146

**Comment by iRoachie** [comment]
Will send another PR that fixes this.

**Pull request closed without merging**
