### PR TITLE
Added tertiaryText Option

### PR DESCRIPTION
**Pull request by mbenjamin618**
Added the option to start a third line of text in the ListItem instead of having it automatically wrapped.

### CODE REVIEW

**Comment by xotahal** [comment]
Hey @mbenjamin618 :) And sorry for delay ... I'm still not sure about this feature. Is there posibility how we could approach what you want to approach only with `primary` and `secondary` lines?

I'm not saying we don't need tertiaryText, but I would just like to know it's necessary.

**Comment by mbenjamin618** [comment]
@xotahal Thanks for the response! So far, I've been using the tertiaryText feature in my code on all of the cards I've used. Maybe a way to only have a primary and secondary text option is to recognize a character (\n) from the inputted text to start a new line? This solution seems more complicated than having a third line prop (like tertiaryText) though.

**Comment by HofmannZ** [comment]
@mbenjamin618 I don't understand, you can just use `numberOfLines={3}` prop or set the prop to `dynamic`. Though reading through [specs](https://material.io/guidelines/components/lists.html#lists-specs) it show a bold subheader in some tiles, but thats somthing differnd form the rapping issue.

**Comment by mbenjamin618** [comment]
@HofmannZ you can do both of the solutions you mentioned, but that doesn't allow you to choose what starts on each line. With my addition, you are now able to choose what starts on the third line. For example, if you want to show two different dates on the second and third line in the current implementation you'd have to add spaces to the end of the second line to have the second date start on the third line. With mine, you'd set date1 to the second line and date2 to the tertiaryText prop.

**Comment by xotahal** [comment]
Yeah, it makes sense. I just have to check everything in [demo app](https://github.com/xotahal/react-native-material-ui-demo-app). Because it probably changes a behaviour of `numberOfLines`. If someone choose `dynamic` as a value of `numberOfLines`, it makes dynamic everything, or just second or third line? And if someone choose `3`? Then second line has 2 lines if there is no third line? Or 1 and third line has 1 as well if exists?

We probably need it .. but we should probably document that :)

**Comment by mbenjamin618** [comment]
None of the functionality changed with dynamic, I just added the option to add a third line.

**Comment by xotahal** [comment]
Thanks @mbenjamin618

**Pull request merged**
