### PR TITLE
Add Card documentation

### PR DESCRIPTION
**Pull request by andrewda**
Currently there is no documentation for the Card component, one of the most popular components in my experience. This will add some basic documentation so people can get started using it without having to dig around in the source too much, even though it's pretty easy to use.

### CODE REVIEW

**Comment by jayesbe** [comment]
I am trying to implement a Card at the moment and using the trivial use case in the doc I keep getting this error,

undefined is not an object (evaluating 'context.uiTheme.card')
getStyles
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:67776:31
render
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:67809:35
<unknown>
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15839:27
measureLifeCyclePerf
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15299:14
_renderValidatedComponentWithoutOwnerOrContext
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15838:45
_renderValidatedComponent
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15859:78
performInitialMount
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15511:55
mountComponent
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15414:40
mountComponent
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:14450:49
mountChildren
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:14895:56
initializeChildren
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:13200:41
mountComponent
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:13283:28
mountComponent
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:14450:49
performInitialMount
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15519:48
mountComponent
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15414:40
mountComponent
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:14450:49
performInitialMount
    index.android.bundle?platform=android&dev=true&hot=true&minify=false:15519:48
`
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import { Card } from 'react-native-material-ui';

export default class InsightCard extends Component {
  render() {
    return (
      <View>
        <Card style={{
          container: {
            borderRadius: 2,
            marginVertical: 4,
            marginHorizontal: 8,
          }
        }}>
          <View>
            <Text>Hello world!</Text>
          </View>
        </Card>
      </View>
    );
  }
}
`

It's really doesn't make sense to me..

**Comment by jayesbe** [comment]
Nevermind.. I re-read the repo main readme.. missing the UI theme.

**Comment by RobertSheaO** [comment]
Why is it that the "Welcome" card shown in the screenshot isn't in the demo app?

**Comment by andrewda** [comment]
@RobertSheaO many of the screenshots in this repo are from the `react-native-material-design` demo app, for some reason, instead of this one.

**Comment by xotahal** [comment]
@RobertSheaO as said @andrewda, it was forked from react-native-material-design. But then I was reliazed we need something more like material-ui (on web). So I completely redesign it to be more customable. And I have not documented properly yet :(

**Comment by andrewda** [comment]
It would probably be nice to have something card-wise more similar to `react-native-material-design`. Instead of just having a `<Card>` component, we should also have `<Card.Header>`, `<Card.Body>` and `<Card.Actions>` so that the styling is better.

**Pull request merged**
