### PR TITLE
[ActionButton] Add support for custom icons in actions.

### PR DESCRIPTION
**Pull request by NewOldMax**
Add support for custom icon elements for ActionButton actions instead of names, like #62

### CODE REVIEW

**Comment by NewOldMax** [comment]
Found issue with array of elements, working on it

**Comment by ppm-souvik** [comment]
If action button icon's support custom icons, why the action Button icon only supports strings?

**Comment by NewOldMax** [comment]
As I see [in sources](https://github.com/xotahal/react-native-material-ui/blob/master/src/Button/Button.react.js#L43), button supports custom icons

**Comment by ppm-souvik** [comment]
@NewOldMax I was referring to [ActionButtons](https://github.com/xotahal/react-native-material-ui/blob/master/src/ActionButton/ActionButton.react.js#L53)

**Pull request merged**
