### PR TITLE
Dialog is having ripple effect

### PR DESCRIPTION
**Pull request by riteshmalav**
Dialog in android is showing ripple effect. I believe this will make the change.

### CODE REVIEW

**Comment by xotahal** [comment]
Why do you think there should be no ripple for dialog?

**Comment by riteshmalav** [comment]
That is how the standard behaviour of dialog should be.

**Comment by xotahal** [comment]
According what? Could you send me a link to study? And how you catch onPress then?

**Comment by riteshmalav** [comment]
Well a dialog is more of a modified version of an alert and we don't see ripple effect in android alerts.

**Comment by riteshmalav** [comment]
an example can be whenever you visit a mail in gmail app and click on top right button and try to report it as span and dialog box will open up and that dialog box does not have ripple effect. I believe since google owns that application they would have implemented it accordingly.

**Comment by riteshmalav** [comment]
i believe this https://github.com/xotahal/react-native-material-ui/pull/279/commits/c869739e582727f842329967fdc5251368d30ae0 change will take care of the onPress();

**Comment by xotahal** [comment]
View's onpress can't work i think .. and about ripple .. i believe you are able to find plenty of examples of dialogs that doesn't have onPress at all .. but at same time, you can find a dialogs that have onPress and ripple effect .. i believe that even the google has implemented that in some app ..

**Comment by riteshmalav** [comment]
Well as of now i have not seen any app that has ripple effect on the full popup window but still if we want to keep it we can have it as props so that user can have the ripple effect if he needs it or otherwise.

**Comment by xotahal** [comment]
I think it should be prop of RippleFeedback component ..

If there is no `onPress` we should have avoided to render Ripple effect ...

**Comment by riteshmalav** [comment]
No it shall not be, that way we are violating the RippleFeedback component. Use of the RippleFeedback component is to provide ripple to another component. If you remove ripple from RippleFeedback component then its like having an empty component (RippleFeedback) that makes no sense.

**Comment by riteshmalav** [comment]
Or just make it simple, since most of the dialog box does not have ripple effect we can remove it  completely. That way we don't need to handle it. Shall i create one pull request.

**Comment by xotahal** [comment]
But we can remove ripple effect from RippleFeedback only if there is no onPress method. Because it doesn't make sense to have an UI feedback for component that doesn't have event listener.

Then you can remove feedback effect from any component any time, only by remove onPress prop ...

**Comment by xotahal** [comment]
I am going to close this since I think Dialog can have RippleFeedback. We can remove RippleFeedback directly in RippleFeedback component if there is no onPress method.

**Comment by riteshmalav** [comment]
Sorry for the delay, i was out, how about we pass one prop to Dialog container <Dialog ripple={false}> that will disable the native <TouchableNativeFeedback> that falls under RippleFeedback container.

**Pull request closed without merging**
