### PR TITLE
Mock iOS backButton when searching

### PR DESCRIPTION
**Pull request by owebmaster**

### CODE REVIEW

**Comment by xotahal** [comment]
Hey @owebmaster, thank you for this pull request. Since the react native itself fixes this issue, could we use the native solution? https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Utilities/BackAndroid.ios.js

So, this code should fix it:
```js
const addBackButtonListener = (callback) =>
    BackAndroid.addEventListener('closeRequested', callback);
```

Could you check it please?

**Comment by owebmaster** [comment]
Nice! What need to be done so is remove the iOS check? (they should change the name of this lib, BackAndroid for iOS doesn't feels fine :P)

**Comment by xotahal** [comment]
Yeah, but it makes sense. BackAndroid is "Back for Android" and since the iOS doesn't have back button they mocked BackAndroid component to return emptyFunction.

You don't have to make a new pull request. Just delete the iOS check, else statement, try if it works and make new commit please ;)

**Comment by xotahal** [comment]
Resolved here - https://github.com/xotahal/react-native-material-ui/pull/54

**Pull request closed without merging**
